quarkus.index-dependency.rimfrost-framework-erbjudande-topic-adapter.group-id=se.fk.rimfrost.framework.erbjudande.topic
quarkus.index-dependency.rimfrost-framework-erbjudande-topic-adapter.artifact-id=rimfrost-framework-erbjudande-topic-adapter
quarkus.index-dependency.rimfrost-framework-handlaggning-adapter.group-id=se.fk.rimfrost.framework.handlaggning
quarkus.index-dependency.rimfrost-framework-handlaggning-adapter.artifact-id=rimfrost-framework-handlaggning-adapter
quarkus.index-dependency.rimfrost-service-workflow-openapi-jaxrs-spec.group-id=se.fk.rimfrost.workflow
quarkus.index-dependency.rimfrost-service-workflow-openapi-jaxrs-spec.artifact-id=rimfrost-service-workflow-openapi-jaxrs-spec

rimfrost.yrkande.default.yrkande-status.id=e27da561-a8db-4513-8272-ef652b097b16
rimfrost.producerat-resultat.default.yrkande-status.id=e27da561-a8db-4513-8272-ef652b097b16

quarkus.hibernate-validator.method-validation.allow-overriding-parameter-constraints=true

# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-service-workflow
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false

# Kafka
# Deserializer
mp.messaging.incoming.handlaggning-responses.value.deserializer=se.fk.github.rimfrost.workflow.presentation.kafka.HandlaggningResponseMessagePayloadDeserializer

# Serializer
mp.messaging.outgoing.handlaggning-requests.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.handlaggning-done.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

#Incoming
mp.messaging.incoming.handlaggning-responses.connector=smallrye-kafka
mp.messaging.incoming.handlaggning-responses.topic=handlaggning-responses
mp.messaging.incoming.handlaggning-responses.auto.offset.reset=earliest

#Outgoing
mp.messaging.outgoing.handlaggning-requests.connector=smallrye-kafka
mp.messaging.outgoing.handlaggning-done.connector=smallrye-kafka
mp.messaging.outgoing.handlaggning-done.topic=handlaggning-done

%dev.quarkus.kafka.devservices.enabled=true

# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.database.default-schema=${quarkus.flyway.default-schema}
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.flyway.migrate-at-start=true
quarkus.flyway.create-schemas=true
quarkus.flyway.schemas=${quarkus.flyway.default-schema}
quarkus.flyway.default-schema=workflow

%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

%dev.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.enabled=true

# Adapter configuration

%dev.handlaggning.api.base-url=http://localhost:8080
%dev.erbjudande.topic.api.base-url=http://localhost:8080

handlaggning.api.base-url=http://rimfrost-k8s-handlaggning:8080
erbjudande.topic.api.base-url=http://rimfrost-k8s-erbjudande-topic:8080
